name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-ec2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rsync to EC2
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          REMOTE_PORT: ${{ secrets.EC2_PORT }}
          SOURCE: .
          TARGET: ${{ secrets.EC2_PATH }}
          ARGS: >
            -avz --delete
            --exclude='.git/'
            --exclude='node_modules/'
            --exclude='.github/'
            --exclude='client/.env'
            --exclude='server/.env'

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            set -e
            cd ${{ secrets.EC2_PATH }}
            test -f server/.env || { echo "server/.env missing"; exit 1; }
            test -f client/.env || { echo "client/.env missing"; exit 1; }
            docker-compose up -d --build --remove-orphans
            docker-compose ps
